from harbor.dsite.io/devops-cloud/k8s-cloud-system-cli/main/jenkins:1.2.6

USER root

RUN apt-get update && \
    apt-get install --no-install-recommends -qy \
    zlib1g-dev libjpeg-dev libmagic-dev libmagickwand-dev xvfb poppler-utils libfile-mimeinfo-perl qpdf libimage-exiftool-perl \
    ffmpeg lzma liblzma-dev libbz2-dev libsqlite3-dev rabbitmq-server pipx

RUN curl -O https://www.python.org/ftp/python/3.11.8/Python-3.11.8.tgz && \
    tar -xvzf Python-3.11.8.tgz && \
    cd Python-3.11.8 && \
    ./configure --enable-optimizations --enable-loadable-sqlite-extensions && \
    make && \
    make install

RUN curl -O https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tgz && \
    tar -xvzf Python-3.12.2.tgz && \
    cd Python-3.12.2 && \
    ./configure --enable-optimizations --enable-loadable-sqlite-extensions && \
    make && \
    make install

RUN pip install poetry nox

RUN curl -OL --output-dir /tmp https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.xz && \
	echo "c8c5fa53ce0c0f248e45983e86368e0b1daf84b77e88b310f769c3cfc12682ef  /tmp/node-v18.15.0-linux-x64.tar.xz" | shasum --check - && \
	tar xf /tmp/node-v18.15.0-linux-x64.tar.xz --strip-components 1 -C /usr/local && \
    npm install -g azurite

USER jenkins
